use jackbot_instrument::{
    asset::{name::AssetNameExchange, AssetIndex},
    exchange::ExchangeId,
    instrument::{name::InstrumentNameExchange, InstrumentIndex},
};
use jackbot_integration::error::SocketError;
use serde::{Deserialize, Serialize};
use std::time::Duration;
use thiserror::Error;

/// Type alias for a [`ClientError`] that is keyed on [`AssetNameExchange`] and
/// [`InstrumentNameExchange`] (yet to be indexed).
pub type UnindexedClientError = ClientError<AssetNameExchange, InstrumentNameExchange>;

/// Type alias for a [`ApiError`] that is keyed on [`AssetNameExchange`] and
/// [`InstrumentNameExchange`] (yet to be indexed).
pub type UnindexedApiError = ApiError<AssetNameExchange, InstrumentNameExchange>;

/// Type alias for a [`OrderError`] that is keyed on [`AssetNameExchange`] and
/// [`InstrumentNameExchange`] (yet to be indexed).
pub type UnindexedOrderError = OrderError<AssetNameExchange, InstrumentNameExchange>;

/// Represents all errors produced by an [`ExecutionClient`](super::client::ExecutionClient).
#[derive(Debug, Clone, Eq, PartialEq, Ord, PartialOrd, Hash, Deserialize, Serialize, Error)]
pub enum ClientError<AssetKey = AssetIndex, InstrumentKey = InstrumentIndex> {
    /// Connectivity based error.
    ///
    /// eg/ Timeout.
    #[error("Connectivity: {0}")]
    Connectivity(#[from] ConnectivityError),

    /// API based error.
    ///
    /// eg/ RateLimit.
    #[error("API: {0}")]
    Api(#[from] ApiError<AssetKey, InstrumentKey>),

    /// Failed to fetch an AccountSnapshot.
    #[error("failed to fetch AccountSnapshot: {0}")]
    AccountSnapshot(String),

    /// Failed to initialise an AccountStream.
    #[error("failed to init AccountStream: {0}")]
    AccountStream(String),

    /// Generic other error.
    #[error("Other: {0}")]
    Other(String),
}

/// Represents all connectivity-centric errors.
///
/// Connectivity errors are generally intermittent / non-deterministic (eg/ Timeout).
#[derive(Debug, Clone, Eq, PartialEq, Ord, PartialOrd, Hash, Deserialize, Serialize, Error)]
pub enum ConnectivityError {
    /// Indicates an exchange is offline, likely due to maintenance.
    #[error("Exchange offline: {0}")]
    ExchangeOffline(ExchangeId),

    /// Indicates an ExecutionRequest timed out before a response was received.
    #[error("ExecutionRequest timed out")]
    Timeout,

    /// Represents a [`SocketError`] generated by an execution integration.
    #[error("{0}")]
    Socket(String),
}

impl From<SocketError> for ConnectivityError {
    fn from(value: SocketError) -> Self {
        Self::Socket(value.to_string())
    }
}

/// Represents all API errors generated by an exchange.
///
/// These typically indicate a request is invalid for some reason (eg/ BalanceInsufficient).
#[derive(Debug, Clone, Eq, PartialEq, Ord, PartialOrd, Hash, Deserialize, Serialize, Error)]
pub enum ApiError<AssetKey = AssetIndex, InstrumentKey = InstrumentIndex> {
    /// Provided asset identifier is invalid or not supported.
    ///
    /// For example:
    /// - The [`AssetNameExchange`] was an invalid format.
    #[error("asset {0} invalid: {1}")]
    AssetInvalid(AssetKey, String),

    /// Provided instrument identifier is invalid or not supported.
    ///
    /// For example:
    /// - The exchange does not have a market for an instrument.
    /// - The [`InstrumentNameExchange`] was an invalid format.
    #[error("instrument {0} invalid: {1}")]
    InstrumentInvalid(InstrumentKey, String),

    #[error("rate limit exceeded")]
    RateLimit,
    #[error("asset {0} balance insufficient: {1}")]
    BalanceInsufficient(AssetKey, String),
    #[error("order rejected: {0}")]
    OrderRejected(String),
    #[error("order already cancelled")]
    OrderAlreadyCancelled,
    #[error("order already fully filled")]
    OrderAlreadyFullyFilled,
}

/// Represents all errors that can be generated when cancelling or opening orders.
#[derive(Debug, Clone, Eq, PartialEq, Ord, PartialOrd, Hash, Deserialize, Serialize, Error)]
pub enum OrderError<AssetKey = AssetIndex, InstrumentKey = InstrumentIndex> {
    /// Connectivity based error.
    ///
    /// eg/ Timeout.
    #[error("connectivity: {0}")]
    Connectivity(#[from] ConnectivityError),

    /// API based error.
    ///
    /// eg/ RateLimit.
    #[error("order rejected: {0}")]
    Rejected(#[from] ApiError<AssetKey, InstrumentKey>),
}

/// Represents errors related to exchange, asset and instrument identifier key lookups.
#[derive(Debug, Clone, Eq, PartialEq, Ord, PartialOrd, Hash, Deserialize, Serialize, Error)]
pub enum KeyError {
    /// Indicates an [`ExchangeId`] was encountered that was not indexed, so does not have a
    /// corresponding `ExchangeIndex`.
    #[error("ExchangeId: {0}")]
    ExchangeId(String),

    /// Indicates an [`AssetNameExchange`] was encountered that was not indexed, so does not have a
    /// corresponding [`AssetIndex`].
    #[error("AssetKey: {0}")]
    AssetKey(String),

    /// Indicates an [`InstrumentNameExchange`] was encountered that was no indexed, so does
    /// not have a corresponding [`InstrumentIndex`].
    #[error("InstrumentKey: {0}")]
    InstrumentKey(String),
}

/// Type alias for sensor-specific errors.
pub type SensorOrderError = SensorError<AssetNameExchange, InstrumentNameExchange>;

/// Represents errors specific to sensor-based order execution and processing.
#[derive(Debug, Clone, PartialEq, Deserialize, Serialize, Error)]
pub enum SensorError<AssetKey = AssetIndex, InstrumentKey = InstrumentIndex> {
    /// Underlying order execution error
    #[error("order execution failed: {0}")]
    OrderExecution(#[from] OrderError<AssetKey, InstrumentKey>),

    /// Sensor-specific execution errors
    #[error("jackpot order execution failed: {0}")]
    JackpotExecution(String),

    #[error("prophetic order analysis failed: {0}")]
    PropheticAnalysis(String),

    #[error("event-triggered order failed: {0}")]
    EventTriggeredFailure(String),

    /// Performance and timing errors
    #[error("execution timeout after {timeout:?}: {reason}")]
    ExecutionTimeout { timeout: Duration, reason: String },

    #[error("performance threshold exceeded: {metric} = {value}, threshold = {threshold}")]
    PerformanceThresholdExceeded {
        metric: String,
        value: f64,
        threshold: f64,
    },

    /// Risk management errors
    #[error("risk limit exceeded: {limit_type} = {current_value}, limit = {limit_value}")]
    RiskLimitExceeded {
        limit_type: String,
        current_value: String,
        limit_value: String,
    },

    #[error(
        "position limit exceeded for exchange {exchange}: current = {current}, limit = {limit}"
    )]
    PositionLimitExceeded {
        exchange: ExchangeId,
        current: String,
        limit: String,
    },

    #[error(
        "daily volume limit exceeded for exchange {exchange}: current = {current}, limit = {limit}"
    )]
    DailyVolumeLimitExceeded {
        exchange: ExchangeId,
        current: String,
        limit: String,
    },

    /// Routing and exchange errors
    #[error("no available exchanges for routing")]
    NoAvailableExchanges,

    #[error("exchange {exchange} unavailable: {reason}")]
    ExchangeUnavailable {
        exchange: ExchangeId,
        reason: String,
    },

    #[error("insufficient liquidity on exchange {exchange}: required = {required}, available = {available}")]
    InsufficientLiquidity {
        exchange: ExchangeId,
        required: String,
        available: String,
    },

    #[error(
        "latency threshold exceeded for exchange {exchange}: {latency_ms}ms > {threshold_ms}ms"
    )]
    LatencyThresholdExceeded {
        exchange: ExchangeId,
        latency_ms: u64,
        threshold_ms: u64,
    },

    /// Market condition errors
    #[error("market conditions not suitable for {order_type}: {reason}")]
    UnsuitableMarketConditions { order_type: String, reason: String },

    #[error("volatility too high for execution: {volatility} > {threshold}")]
    VolatilityTooHigh { volatility: f64, threshold: f64 },

    #[error("spread too wide for execution: {spread} > {max_spread}")]
    SpreadTooWide { spread: String, max_spread: String },

    /// Data and analysis errors
    #[error("order book aggregator not found for instrument {instrument}")]
    AggregatorNotFound { instrument: InstrumentKey },

    #[error(
        "insufficient historical data for analysis: required = {required}, available = {available}"
    )]
    InsufficientHistoricalData { required: usize, available: usize },

    #[error("predictive model confidence too low: {confidence} < {threshold}")]
    LowPredictionConfidence { confidence: f64, threshold: f64 },

    #[error("event trigger timeout: waited {wait_time:?} for {event_type}")]
    EventTriggerTimeout {
        wait_time: Duration,
        event_type: String,
    },

    /// System and resource errors
    #[error("system overloaded: {active_orders} orders > {max_orders} limit")]
    SystemOverloaded {
        active_orders: usize,
        max_orders: usize,
    },

    #[error("concurrency limit reached: {active_tasks} >= {max_tasks}")]
    ConcurrencyLimitReached {
        active_tasks: usize,
        max_tasks: usize,
    },

    #[error("memory limit exceeded: {usage_mb}MB > {limit_mb}MB")]
    MemoryLimitExceeded { usage_mb: usize, limit_mb: usize },

    /// Configuration and validation errors
    #[error("invalid sensor order configuration: {field} = {value}, {reason}")]
    InvalidConfiguration {
        field: String,
        value: String,
        reason: String,
    },

    #[error("unsupported order type for sensor execution: {order_type}")]
    UnsupportedOrderType { order_type: String },

    #[error("invalid order parameters: {parameter} = {value}, expected {expected}")]
    InvalidOrderParameters {
        parameter: String,
        value: String,
        expected: String,
    },

    /// Analytics and monitoring errors
    #[error("analytics collection failed: {reason}")]
    AnalyticsFailure { reason: String },

    #[error("performance monitoring disabled: {feature}")]
    MonitoringDisabled { feature: String },

    /// Generic sensor error with context
    #[error("sensor execution error: {context}")]
    SensorExecutionError { context: String },
}

impl<AssetKey, InstrumentKey> SensorError<AssetKey, InstrumentKey> {
    /// Create a timeout error
    pub fn timeout(timeout: Duration, reason: impl Into<String>) -> Self {
        Self::ExecutionTimeout {
            timeout,
            reason: reason.into(),
        }
    }

    /// Create a performance threshold error
    pub fn performance_threshold(metric: impl Into<String>, value: f64, threshold: f64) -> Self {
        Self::PerformanceThresholdExceeded {
            metric: metric.into(),
            value,
            threshold,
        }
    }

    /// Create a risk limit error
    pub fn risk_limit(
        limit_type: impl Into<String>,
        current_value: impl Into<String>,
        limit_value: impl Into<String>,
    ) -> Self {
        Self::RiskLimitExceeded {
            limit_type: limit_type.into(),
            current_value: current_value.into(),
            limit_value: limit_value.into(),
        }
    }

    /// Create an exchange unavailable error
    pub fn exchange_unavailable(exchange: ExchangeId, reason: impl Into<String>) -> Self {
        Self::ExchangeUnavailable {
            exchange,
            reason: reason.into(),
        }
    }

    /// Create a market conditions error
    pub fn unsuitable_market_conditions(
        order_type: impl Into<String>,
        reason: impl Into<String>,
    ) -> Self {
        Self::UnsuitableMarketConditions {
            order_type: order_type.into(),
            reason: reason.into(),
        }
    }

    /// Create a system overload error
    pub fn system_overloaded(active_orders: usize, max_orders: usize) -> Self {
        Self::SystemOverloaded {
            active_orders,
            max_orders,
        }
    }

    /// Create a generic sensor error with context
    pub fn with_context(context: impl Into<String>) -> Self {
        Self::SensorExecutionError {
            context: context.into(),
        }
    }
}

// Implement From<String> for convenient error creation
impl<AssetKey, InstrumentKey> From<String> for SensorError<AssetKey, InstrumentKey> {
    fn from(context: String) -> Self {
        Self::SensorExecutionError { context }
    }
}

impl<AssetKey, InstrumentKey> From<&str> for SensorError<AssetKey, InstrumentKey> {
    fn from(context: &str) -> Self {
        Self::SensorExecutionError {
            context: context.to_string(),
        }
    }
}
