name: Enable auto-merge

on:
  pull_request_target:
    types: [opened, reopened, ready_for_review]

permissions:
  pull-requests: write

jobs:
  enable:
    runs-on: ubuntu-latest
    steps:
      - name: Enable auto-merge on this PR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL:  ${{ github.event.pull_request.html_url }}
        run: gh pr merge --auto --merge "$PR_URL"
